<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="AutoMapper" Version="13.0.1" />
	  <PackageReference Include="FluentValidation" Version="12.1.1" />
	  <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourseFlow.Application\CourseFlow.Application.csproj" />
    <ProjectReference Include="..\CourseFlow.Domain\CourseFlow.Domain.csproj" />
    <ProjectReference Include="..\CourseFlow.Infrastructure\CourseFlow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
